version: '3'
services:
  frontend-service:
    build: ./frontend
    container_name: chouseisan-frontend-container
    volumes:
      - ./frontend:/app/frontend
    tty: true
    ports:
      - "3000:3000"
    command: sh -c "npm start"

  backend-service:
    build: ./backend
    container_name: chouseisan-backend-container
    tty: true
    ports:
      - "8080:8080"
